services:
  db:
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lms_db
      - POSTGRES_USER=manoj
      - POSTGRES_PASSWORD=strongpassword
    ports:
      - "5432:5432"

 