# Generated by Django 6.0.1 on 2026-02-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='drive_link',
            new_name='link',
        ),
    ]
