# Generated by Django 6.0.1 on 2026-03-21 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_course_quiz_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('points_earned', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizsubmission')),
            ],
        ),
    ]
