# Generated by Django 6.0.1 on 2026-03-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizsubmission_is_graded_alter_quizsubmission_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_points',
            field=models.IntegerField(default=1),
        ),
    ]
