# Generated by Django 6.0.1 on 2026-02-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_comment_is_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
