# Generated by Django 6.0.1 on 2026-02-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lectureprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectureprogress',
            old_name='compeleted',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='lectureprogress',
            old_name='compeleted_at',
            new_name='completed_at',
        ),
    ]
