# Generated by Django 6.0.1 on 2026-03-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_tag_course_difficulty_course_is_free_course_language_and_more'),
        ('courses', '0008_seed_tags'),
    ]

    operations = [
    ]
