# Generated by Django 6.0.1 on 2026-03-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_review'),
        ('courses', '0009_merge_20260320_0649'),
    ]

    operations = [
    ]
