# Generated by Django 6.0.1 on 2026-05-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_enrollment_is_paid_courseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lecture_videos/'),
        ),
    ]
